/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Range from './Range';
import SyntaxNode from './SyntaxNode';

/**
 * The ApplAllOf model module.
 * @module model/ApplAllOf
 * @version 1.1.3
 */
class ApplAllOf {
    /**
     * Constructs a new <code>ApplAllOf</code>.
     * @alias module:model/ApplAllOf
     * @param error {Boolean} 
     * @param missing {Boolean} 
     * @param range {module:model/Range} 
     * @param symbol {String} 
     */
    constructor(error, missing, range, symbol) { 
        
        ApplAllOf.initialize(this, error, missing, range, symbol);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, error, missing, range, symbol) { 
        obj['error'] = error || false;
        obj['missing'] = missing || false;
        obj['range'] = range;
        obj['symbol'] = symbol || '';
    }

    /**
     * Constructs a <code>ApplAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplAllOf} obj Optional instance to populate.
     * @return {module:model/ApplAllOf} The populated <code>ApplAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplAllOf();

            if (data.hasOwnProperty('arguments')) {
                obj['arguments'] = ApiClient.convertToType(data['arguments'], [SyntaxNode]);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'Boolean');
            }
            if (data.hasOwnProperty('missing')) {
                obj['missing'] = ApiClient.convertToType(data['missing'], 'Boolean');
            }
            if (data.hasOwnProperty('range')) {
                obj['range'] = Range.constructFromObject(data['range']);
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/SyntaxNode>} arguments
 */
ApplAllOf.prototype['arguments'] = undefined;

/**
 * @member {Boolean} error
 * @default false
 */
ApplAllOf.prototype['error'] = false;

/**
 * @member {Boolean} missing
 * @default false
 */
ApplAllOf.prototype['missing'] = false;

/**
 * @member {module:model/Range} range
 */
ApplAllOf.prototype['range'] = undefined;

/**
 * @member {String} symbol
 * @default ''
 */
ApplAllOf.prototype['symbol'] = '';






export default ApplAllOf;

