/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PairSymbolString from './PairSymbolString';

/**
 * The AzureIntegrationAllOf model module.
 * @module model/AzureIntegrationAllOf
 * @version 1.1.3
 */
class AzureIntegrationAllOf {
    /**
     * Constructs a new <code>AzureIntegrationAllOf</code>.
     * @alias module:model/AzureIntegrationAllOf
     */
    constructor() { 
        
        AzureIntegrationAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AzureIntegrationAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AzureIntegrationAllOf} obj Optional instance to populate.
     * @return {module:model/AzureIntegrationAllOf} The populated <code>AzureIntegrationAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AzureIntegrationAllOf();

            if (data.hasOwnProperty('credentials')) {
                obj['credentials'] = ApiClient.convertToType(data['credentials'], [PairSymbolString]);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('storage_allowed_locations')) {
                obj['storage_allowed_locations'] = ApiClient.convertToType(data['storage_allowed_locations'], ['String']);
            }
            if (data.hasOwnProperty('storage_blocked_locations')) {
                obj['storage_blocked_locations'] = ApiClient.convertToType(data['storage_blocked_locations'], ['String']);
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/PairSymbolString>} credentials
 */
AzureIntegrationAllOf.prototype['credentials'] = undefined;

/**
 * @member {String} name
 */
AzureIntegrationAllOf.prototype['name'] = undefined;

/**
 * @member {Array.<String>} storage_allowed_locations
 */
AzureIntegrationAllOf.prototype['storage_allowed_locations'] = undefined;

/**
 * @member {Array.<String>} storage_blocked_locations
 */
AzureIntegrationAllOf.prototype['storage_blocked_locations'] = undefined;

/**
 * @member {String} tenant_id
 */
AzureIntegrationAllOf.prototype['tenant_id'] = undefined;






export default AzureIntegrationAllOf;

