/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CardinalityActionAllOf model module.
 * @module model/CardinalityActionAllOf
 * @version 1.1.3
 */
class CardinalityActionAllOf {
    /**
     * Constructs a new <code>CardinalityActionAllOf</code>.
     * @alias module:model/CardinalityActionAllOf
     */
    constructor() { 
        
        CardinalityActionAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CardinalityActionAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CardinalityActionAllOf} obj Optional instance to populate.
     * @return {module:model/CardinalityActionAllOf} The populated <code>CardinalityActionAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CardinalityActionAllOf();

            if (data.hasOwnProperty('relname')) {
                obj['relname'] = ApiClient.convertToType(data['relname'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} relname
 */
CardinalityActionAllOf.prototype['relname'] = undefined;






export default CardinalityActionAllOf;

