/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ClientProblemAllOf model module.
 * @module model/ClientProblemAllOf
 * @version 1.1.3
 */
class ClientProblemAllOf {
    /**
     * Constructs a new <code>ClientProblemAllOf</code>.
     * @alias module:model/ClientProblemAllOf
     * @param errorCode {String} 
     * @param isError {Boolean} 
     * @param isException {Boolean} 
     * @param message {String} 
     * @param path {String} 
     * @param report {String} 
     */
    constructor(errorCode, isError, isException, message, path, report) { 
        
        ClientProblemAllOf.initialize(this, errorCode, isError, isException, message, path, report);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, errorCode, isError, isException, message, path, report) { 
        obj['error_code'] = errorCode || '';
        obj['is_error'] = isError || false;
        obj['is_exception'] = isException || false;
        obj['message'] = message || '';
        obj['path'] = path || '';
        obj['report'] = report || '';
    }

    /**
     * Constructs a <code>ClientProblemAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClientProblemAllOf} obj Optional instance to populate.
     * @return {module:model/ClientProblemAllOf} The populated <code>ClientProblemAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClientProblemAllOf();

            if (data.hasOwnProperty('error_code')) {
                obj['error_code'] = ApiClient.convertToType(data['error_code'], 'String');
            }
            if (data.hasOwnProperty('is_error')) {
                obj['is_error'] = ApiClient.convertToType(data['is_error'], 'Boolean');
            }
            if (data.hasOwnProperty('is_exception')) {
                obj['is_exception'] = ApiClient.convertToType(data['is_exception'], 'Boolean');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('report')) {
                obj['report'] = ApiClient.convertToType(data['report'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} error_code
 * @default ''
 */
ClientProblemAllOf.prototype['error_code'] = '';

/**
 * @member {Boolean} is_error
 * @default false
 */
ClientProblemAllOf.prototype['is_error'] = false;

/**
 * @member {Boolean} is_exception
 * @default false
 */
ClientProblemAllOf.prototype['is_exception'] = false;

/**
 * @member {String} message
 * @default ''
 */
ClientProblemAllOf.prototype['message'] = '';

/**
 * @member {String} path
 * @default ''
 */
ClientProblemAllOf.prototype['path'] = '';

/**
 * @member {String} report
 * @default ''
 */
ClientProblemAllOf.prototype['report'] = '';






export default ClientProblemAllOf;

