/**
 * RAI Cloud SDK
 * This is a Client SDK for RAI Cloud
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ComputeEventInfo model module.
 * @module model/ComputeEventInfo
 * @version 1.4.0
 */
class ComputeEventInfo {
    /**
     * Constructs a new <code>ComputeEventInfo</code>.
     * @alias module:model/ComputeEventInfo
     */
    constructor() { 
        
        ComputeEventInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ComputeEventInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ComputeEventInfo} obj Optional instance to populate.
     * @return {module:model/ComputeEventInfo} The populated <code>ComputeEventInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComputeEventInfo();

            if (data.hasOwnProperty('event_id')) {
                obj['event_id'] = ApiClient.convertToType(data['event_id'], 'String');
            }
            if (data.hasOwnProperty('account_name')) {
                obj['account_name'] = ApiClient.convertToType(data['account_name'], 'String');
            }
            if (data.hasOwnProperty('compute_id')) {
                obj['compute_id'] = ApiClient.convertToType(data['compute_id'], 'String');
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} event_id
 */
ComputeEventInfo.prototype['event_id'] = undefined;

/**
 * @member {String} account_name
 */
ComputeEventInfo.prototype['account_name'] = undefined;

/**
 * @member {String} compute_id
 */
ComputeEventInfo.prototype['compute_id'] = undefined;

/**
 * @member {String} event
 */
ComputeEventInfo.prototype['event'] = undefined;

/**
 * @member {Date} time
 */
ComputeEventInfo.prototype['time'] = undefined;






export default ComputeEventInfo;

