/**
 * RAI Cloud SDK
 * This is a Client SDK for RAI Cloud
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ComputeCreditsInfo model module.
 * @module model/ComputeCreditsInfo
 * @version 1.4.0
 */
class ComputeCreditsInfo {
    /**
     * Constructs a new <code>ComputeCreditsInfo</code>.
     * @alias module:model/ComputeCreditsInfo
     */
    constructor() { 
        
        ComputeCreditsInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ComputeCreditsInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ComputeCreditsInfo} obj Optional instance to populate.
     * @return {module:model/ComputeCreditsInfo} The populated <code>ComputeCreditsInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComputeCreditsInfo();

            if (data.hasOwnProperty('credits')) {
                obj['credits'] = ApiClient.convertToType(data['credits'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} credits
 */
ComputeCreditsInfo.prototype['credits'] = undefined;






export default ComputeCreditsInfo;

