/**
 * RAI Cloud SDK
 * This is a Client SDK for RAI Cloud
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ComputeInfoProtocol model module.
 * @module model/ComputeInfoProtocol
 * @version 1.4.0
 */
class ComputeInfoProtocol {
    /**
     * Constructs a new <code>ComputeInfoProtocol</code>.
     * @alias module:model/ComputeInfoProtocol
     */
    constructor() { 
        
        ComputeInfoProtocol.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ComputeInfoProtocol</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ComputeInfoProtocol} obj Optional instance to populate.
     * @return {module:model/ComputeInfoProtocol} The populated <code>ComputeInfoProtocol</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComputeInfoProtocol();

            if (data.hasOwnProperty('account_name')) {
                obj['account_name'] = ApiClient.convertToType(data['account_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'String');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
            if (data.hasOwnProperty('infrastructure')) {
                obj['infrastructure'] = ApiClient.convertToType(data['infrastructure'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('requested_on')) {
                obj['requested_on'] = ApiClient.convertToType(data['requested_on'], 'String');
            }
            if (data.hasOwnProperty('created_on')) {
                obj['created_on'] = ApiClient.convertToType(data['created_on'], 'String');
            }
            if (data.hasOwnProperty('deleted_on')) {
                obj['deleted_on'] = ApiClient.convertToType(data['deleted_on'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} account_name
 */
ComputeInfoProtocol.prototype['account_name'] = undefined;

/**
 * @member {String} id
 */
ComputeInfoProtocol.prototype['id'] = undefined;

/**
 * @member {String} created_by
 */
ComputeInfoProtocol.prototype['created_by'] = undefined;

/**
 * @member {String} name
 */
ComputeInfoProtocol.prototype['name'] = undefined;

/**
 * @member {String} size
 */
ComputeInfoProtocol.prototype['size'] = undefined;

/**
 * @member {String} region
 */
ComputeInfoProtocol.prototype['region'] = undefined;

/**
 * @member {String} infrastructure
 */
ComputeInfoProtocol.prototype['infrastructure'] = undefined;

/**
 * @member {String} state
 */
ComputeInfoProtocol.prototype['state'] = undefined;

/**
 * @member {String} requested_on
 */
ComputeInfoProtocol.prototype['requested_on'] = undefined;

/**
 * @member {String} created_on
 */
ComputeInfoProtocol.prototype['created_on'] = undefined;

/**
 * @member {String} deleted_on
 */
ComputeInfoProtocol.prototype['deleted_on'] = undefined;

/**
 * @member {String} message
 */
ComputeInfoProtocol.prototype['message'] = undefined;






export default ComputeInfoProtocol;

