/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExceptionProblemAllOf model module.
 * @module model/ExceptionProblemAllOf
 * @version 1.1.3
 */
class ExceptionProblemAllOf {
    /**
     * Constructs a new <code>ExceptionProblemAllOf</code>.
     * @alias module:model/ExceptionProblemAllOf
     * @param exception {String} 
     */
    constructor(exception) { 
        
        ExceptionProblemAllOf.initialize(this, exception);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, exception) { 
        obj['exception'] = exception || '';
    }

    /**
     * Constructs a <code>ExceptionProblemAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExceptionProblemAllOf} obj Optional instance to populate.
     * @return {module:model/ExceptionProblemAllOf} The populated <code>ExceptionProblemAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExceptionProblemAllOf();

            if (data.hasOwnProperty('exception')) {
                obj['exception'] = ApiClient.convertToType(data['exception'], 'String');
            }
            if (data.hasOwnProperty('exception_stacktrace')) {
                obj['exception_stacktrace'] = ApiClient.convertToType(data['exception_stacktrace'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} exception
 * @default ''
 */
ExceptionProblemAllOf.prototype['exception'] = '';

/**
 * @member {String} exception_stacktrace
 */
ExceptionProblemAllOf.prototype['exception_stacktrace'] = undefined;






export default ExceptionProblemAllOf;

