/**
 * RAI Cloud SDK
 * This is a Client SDK for RAI Cloud
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ComputeCreditsInfo from './ComputeCreditsInfo';
import StorageCreditsInfo from './StorageCreditsInfo';

/**
 * The GetAccountCreditsResponse model module.
 * @module model/GetAccountCreditsResponse
 * @version 1.4.0
 */
class GetAccountCreditsResponse {
    /**
     * Constructs a new <code>GetAccountCreditsResponse</code>.
     * @alias module:model/GetAccountCreditsResponse
     */
    constructor() { 
        
        GetAccountCreditsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetAccountCreditsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAccountCreditsResponse} obj Optional instance to populate.
     * @return {module:model/GetAccountCreditsResponse} The populated <code>GetAccountCreditsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAccountCreditsResponse();

            if (data.hasOwnProperty('start_period')) {
                obj['start_period'] = ApiClient.convertToType(data['start_period'], 'Date');
            }
            if (data.hasOwnProperty('end_period')) {
                obj['end_period'] = ApiClient.convertToType(data['end_period'], 'Date');
            }
            if (data.hasOwnProperty('compute')) {
                obj['compute'] = ComputeCreditsInfo.constructFromObject(data['compute']);
            }
            if (data.hasOwnProperty('storage')) {
                obj['storage'] = StorageCreditsInfo.constructFromObject(data['storage']);
            }
        }
        return obj;
    }


}

/**
 * @member {Date} start_period
 */
GetAccountCreditsResponse.prototype['start_period'] = undefined;

/**
 * @member {Date} end_period
 */
GetAccountCreditsResponse.prototype['end_period'] = undefined;

/**
 * @member {module:model/ComputeCreditsInfo} compute
 */
GetAccountCreditsResponse.prototype['compute'] = undefined;

/**
 * @member {module:model/StorageCreditsInfo} storage
 */
GetAccountCreditsResponse.prototype['storage'] = undefined;






export default GetAccountCreditsResponse;

