/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Source from './Source';

/**
 * The InstallActionAllOf model module.
 * @module model/InstallActionAllOf
 * @version 1.1.3
 */
class InstallActionAllOf {
    /**
     * Constructs a new <code>InstallActionAllOf</code>.
     * @alias module:model/InstallActionAllOf
     */
    constructor() { 
        
        InstallActionAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstallActionAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstallActionAllOf} obj Optional instance to populate.
     * @return {module:model/InstallActionAllOf} The populated <code>InstallActionAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstallActionAllOf();

            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], [Source]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Source>} sources
 */
InstallActionAllOf.prototype['sources'] = undefined;






export default InstallActionAllOf;

