/**
 * RAI Cloud SDK
 * This is a Client SDK for RAI Cloud
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ComputeEventInfo from './ComputeEventInfo';

/**
 * The ListComputeEventsResponse model module.
 * @module model/ListComputeEventsResponse
 * @version 1.4.0
 */
class ListComputeEventsResponse {
    /**
     * Constructs a new <code>ListComputeEventsResponse</code>.
     * @alias module:model/ListComputeEventsResponse
     */
    constructor() { 
        
        ListComputeEventsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListComputeEventsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListComputeEventsResponse} obj Optional instance to populate.
     * @return {module:model/ListComputeEventsResponse} The populated <code>ListComputeEventsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListComputeEventsResponse();

            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [ComputeEventInfo]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ComputeEventInfo>} events
 */
ListComputeEventsResponse.prototype['events'] = undefined;






export default ListComputeEventsResponse;

