/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Range from './Range';

/**
 * The LiteralAllOf model module.
 * @module model/LiteralAllOf
 * @version 1.1.3
 */
class LiteralAllOf {
    /**
     * Constructs a new <code>LiteralAllOf</code>.
     * @alias module:model/LiteralAllOf
     * @param missing {Boolean} 
     * @param range {module:model/Range} 
     * @param value {String} 
     */
    constructor(missing, range, value) { 
        
        LiteralAllOf.initialize(this, missing, range, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, missing, range, value) { 
        obj['missing'] = missing || false;
        obj['range'] = range;
        obj['value'] = value || '';
    }

    /**
     * Constructs a <code>LiteralAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LiteralAllOf} obj Optional instance to populate.
     * @return {module:model/LiteralAllOf} The populated <code>LiteralAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LiteralAllOf();

            if (data.hasOwnProperty('missing')) {
                obj['missing'] = ApiClient.convertToType(data['missing'], 'Boolean');
            }
            if (data.hasOwnProperty('range')) {
                obj['range'] = Range.constructFromObject(data['range']);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} missing
 * @default false
 */
LiteralAllOf.prototype['missing'] = false;

/**
 * @member {module:model/Range} range
 */
LiteralAllOf.prototype['range'] = undefined;

/**
 * @member {String} value
 * @default ''
 */
LiteralAllOf.prototype['value'] = '';






export default LiteralAllOf;

