/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RelKey from './RelKey';

/**
 * The ModifyWorkspaceActionResultAllOf model module.
 * @module model/ModifyWorkspaceActionResultAllOf
 * @version 1.1.3
 */
class ModifyWorkspaceActionResultAllOf {
    /**
     * Constructs a new <code>ModifyWorkspaceActionResultAllOf</code>.
     * @alias module:model/ModifyWorkspaceActionResultAllOf
     */
    constructor() { 
        
        ModifyWorkspaceActionResultAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModifyWorkspaceActionResultAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModifyWorkspaceActionResultAllOf} obj Optional instance to populate.
     * @return {module:model/ModifyWorkspaceActionResultAllOf} The populated <code>ModifyWorkspaceActionResultAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModifyWorkspaceActionResultAllOf();

            if (data.hasOwnProperty('delete_edb_result')) {
                obj['delete_edb_result'] = ApiClient.convertToType(data['delete_edb_result'], [RelKey]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/RelKey>} delete_edb_result
 */
ModifyWorkspaceActionResultAllOf.prototype['delete_edb_result'] = undefined;






export default ModifyWorkspaceActionResultAllOf;

