/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Source from './Source';

/**
 * The ParseActionAllOf model module.
 * @module model/ParseActionAllOf
 * @version 1.1.3
 */
class ParseActionAllOf {
    /**
     * Constructs a new <code>ParseActionAllOf</code>.
     * @alias module:model/ParseActionAllOf
     * @param nonterm {String} 
     * @param source {module:model/Source} 
     */
    constructor(nonterm, source) { 
        
        ParseActionAllOf.initialize(this, nonterm, source);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nonterm, source) { 
        obj['nonterm'] = nonterm || '';
        obj['source'] = source;
    }

    /**
     * Constructs a <code>ParseActionAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParseActionAllOf} obj Optional instance to populate.
     * @return {module:model/ParseActionAllOf} The populated <code>ParseActionAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParseActionAllOf();

            if (data.hasOwnProperty('nonterm')) {
                obj['nonterm'] = ApiClient.convertToType(data['nonterm'], 'String');
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = Source.constructFromObject(data['source']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} nonterm
 * @default ''
 */
ParseActionAllOf.prototype['nonterm'] = '';

/**
 * @member {module:model/Source} source
 */
ParseActionAllOf.prototype['source'] = undefined;






export default ParseActionAllOf;

