/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Relation from './Relation';
import Source from './Source';

/**
 * The QueryActionAllOf model module.
 * @module model/QueryActionAllOf
 * @version 1.1.3
 */
class QueryActionAllOf {
    /**
     * Constructs a new <code>QueryActionAllOf</code>.
     * @alias module:model/QueryActionAllOf
     * @param source {module:model/Source} 
     */
    constructor(source) { 
        
        QueryActionAllOf.initialize(this, source);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, source) { 
        obj['source'] = source;
    }

    /**
     * Constructs a <code>QueryActionAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryActionAllOf} obj Optional instance to populate.
     * @return {module:model/QueryActionAllOf} The populated <code>QueryActionAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryActionAllOf();

            if (data.hasOwnProperty('inputs')) {
                obj['inputs'] = ApiClient.convertToType(data['inputs'], [Relation]);
            }
            if (data.hasOwnProperty('outputs')) {
                obj['outputs'] = ApiClient.convertToType(data['outputs'], ['String']);
            }
            if (data.hasOwnProperty('persist')) {
                obj['persist'] = ApiClient.convertToType(data['persist'], ['String']);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = Source.constructFromObject(data['source']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Relation>} inputs
 */
QueryActionAllOf.prototype['inputs'] = undefined;

/**
 * @member {Array.<String>} outputs
 */
QueryActionAllOf.prototype['outputs'] = undefined;

/**
 * @member {Array.<String>} persist
 */
QueryActionAllOf.prototype['persist'] = undefined;

/**
 * @member {module:model/Source} source
 */
QueryActionAllOf.prototype['source'] = undefined;






export default QueryActionAllOf;

