/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Relation from './Relation';

/**
 * The QueryActionResultAllOf model module.
 * @module model/QueryActionResultAllOf
 * @version 1.1.3
 */
class QueryActionResultAllOf {
    /**
     * Constructs a new <code>QueryActionResultAllOf</code>.
     * @alias module:model/QueryActionResultAllOf
     */
    constructor() { 
        
        QueryActionResultAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QueryActionResultAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryActionResultAllOf} obj Optional instance to populate.
     * @return {module:model/QueryActionResultAllOf} The populated <code>QueryActionResultAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryActionResultAllOf();

            if (data.hasOwnProperty('output')) {
                obj['output'] = ApiClient.convertToType(data['output'], [Relation]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Relation>} output
 */
QueryActionResultAllOf.prototype['output'] = undefined;






export default QueryActionResultAllOf;

