/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetOptionsActionAllOf model module.
 * @module model/SetOptionsActionAllOf
 * @version 1.1.3
 */
class SetOptionsActionAllOf {
    /**
     * Constructs a new <code>SetOptionsActionAllOf</code>.
     * @alias module:model/SetOptionsActionAllOf
     */
    constructor() { 
        
        SetOptionsActionAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SetOptionsActionAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetOptionsActionAllOf} obj Optional instance to populate.
     * @return {module:model/SetOptionsActionAllOf} The populated <code>SetOptionsActionAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetOptionsActionAllOf();

            if (data.hasOwnProperty('abort_on_error')) {
                obj['abort_on_error'] = ApiClient.convertToType(data['abort_on_error'], 'Boolean');
            }
            if (data.hasOwnProperty('debug')) {
                obj['debug'] = ApiClient.convertToType(data['debug'], 'Boolean');
            }
            if (data.hasOwnProperty('debug_trace')) {
                obj['debug_trace'] = ApiClient.convertToType(data['debug_trace'], 'Boolean');
            }
            if (data.hasOwnProperty('silent')) {
                obj['silent'] = ApiClient.convertToType(data['silent'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} abort_on_error
 */
SetOptionsActionAllOf.prototype['abort_on_error'] = undefined;

/**
 * @member {Boolean} debug
 */
SetOptionsActionAllOf.prototype['debug'] = undefined;

/**
 * @member {Boolean} debug_trace
 */
SetOptionsActionAllOf.prototype['debug_trace'] = undefined;

/**
 * @member {Boolean} silent
 */
SetOptionsActionAllOf.prototype['silent'] = undefined;






export default SetOptionsActionAllOf;

