/**
 * RAI Cloud SDK
 * This is a Client SDK for RAI Cloud
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StorageCreditsInfo model module.
 * @module model/StorageCreditsInfo
 * @version 1.4.0
 */
class StorageCreditsInfo {
    /**
     * Constructs a new <code>StorageCreditsInfo</code>.
     * @alias module:model/StorageCreditsInfo
     */
    constructor() { 
        
        StorageCreditsInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StorageCreditsInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StorageCreditsInfo} obj Optional instance to populate.
     * @return {module:model/StorageCreditsInfo} The populated <code>StorageCreditsInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageCreditsInfo();

            if (data.hasOwnProperty('credits')) {
                obj['credits'] = ApiClient.convertToType(data['credits'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} credits
 */
StorageCreditsInfo.prototype['credits'] = undefined;






export default StorageCreditsInfo;

