/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PairAnyValueAnyValue from './PairAnyValueAnyValue';
import RelKey from './RelKey';

/**
 * The UpdateActionAllOf model module.
 * @module model/UpdateActionAllOf
 * @version 1.1.3
 */
class UpdateActionAllOf {
    /**
     * Constructs a new <code>UpdateActionAllOf</code>.
     * @alias module:model/UpdateActionAllOf
     * @param rel {module:model/RelKey} 
     */
    constructor(rel) { 
        
        UpdateActionAllOf.initialize(this, rel);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, rel) { 
        obj['rel'] = rel;
    }

    /**
     * Constructs a <code>UpdateActionAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateActionAllOf} obj Optional instance to populate.
     * @return {module:model/UpdateActionAllOf} The populated <code>UpdateActionAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateActionAllOf();

            if (data.hasOwnProperty('delta')) {
                obj['delta'] = ApiClient.convertToType(data['delta'], [PairAnyValueAnyValue]);
            }
            if (data.hasOwnProperty('rel')) {
                obj['rel'] = RelKey.constructFromObject(data['rel']);
            }
            if (data.hasOwnProperty('updates')) {
                obj['updates'] = ApiClient.convertToType(data['updates'], [PairAnyValueAnyValue]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/PairAnyValueAnyValue>} delta
 */
UpdateActionAllOf.prototype['delta'] = undefined;

/**
 * @member {module:model/RelKey} rel
 */
UpdateActionAllOf.prototype['rel'] = undefined;

/**
 * @member {Array.<module:model/PairAnyValueAnyValue>} updates
 */
UpdateActionAllOf.prototype['updates'] = undefined;






export default UpdateActionAllOf;

